# Generated by Django 5.0.2 on 2024-02-24 14:21

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusName', models.CharField(max_length=60, default='', blank=True, null=False)),
                ('state', models.CharField(max_length=2, default='', blank=True, null=False)),
                ('campusId', models.IntegerField(default='', blank=True, null=False)),

            ],
            options={
                'verbose_name_plural': 'University Campuses',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
